// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParliamentApp.Infrastructure.Data;

namespace ParliamentApp.Migrations
{
    [DbContext(typeof(ParliamentContext))]
    [Migration("20210502140935_RenameVoteValue")]
    partial class RenameVoteValue
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ParliamentApp.Models.Entities.ParliamentPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset?>("EndDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("ParliamentNumber")
                        .HasColumnType("int");

                    b.Property<int>("SessionNumber")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ParliamentNumber", "SessionNumber")
                        .IsUnique();

                    b.ToTable("ParliamentPeriods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ParliamentNumber = 43,
                            SessionNumber = 2,
                            StartDate = new DateTimeOffset(new DateTime(2020, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 2,
                            EndDate = new DateTimeOffset(new DateTime(2019, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ParliamentNumber = 43,
                            SessionNumber = 1,
                            StartDate = new DateTimeOffset(new DateTime(2019, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("ParliamentApp.Models.MemberOfParliament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CaucusShortName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConstituencyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ConstituencyProvinceTerritoryName")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("FromDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ParliamentPeriodId")
                        .HasColumnType("int");

                    b.Property<int>("ParliamentPersonId")
                        .HasColumnType("int");

                    b.Property<string>("PersonOfficialFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonOfficialLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonShortHonorific")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ToDateTime")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ParliamentPeriodId");

                    b.ToTable("MembersOfParliament");
                });

            modelBuilder.Entity("ParliamentApp.Models.MemberVote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MemberOfParliamentId")
                        .HasColumnType("int");

                    b.Property<int>("VoteId")
                        .HasColumnType("int");

                    b.Property<int>("VoteValue")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MemberOfParliamentId");

                    b.HasIndex("VoteId");

                    b.ToTable("MemberVotes");
                });

            modelBuilder.Entity("ParliamentApp.Models.Vote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BillNumberCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DecisionDivisionDocumentTypeId")
                        .HasColumnType("int");

                    b.Property<string>("DecisionDivisionDocumentTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DecisionDivisionNumber")
                        .HasColumnType("int");

                    b.Property<int>("DecisionDivisionNumberOfNays")
                        .HasColumnType("int");

                    b.Property<int>("DecisionDivisionNumberOfPaired")
                        .HasColumnType("int");

                    b.Property<int>("DecisionDivisionNumberOfYeas")
                        .HasColumnType("int");

                    b.Property<string>("DecisionDivisionSubject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("DecisionEventDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DecisionResultName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParliamentPeriodId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParliamentPeriodId");

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("ParliamentApp.Models.MemberOfParliament", b =>
                {
                    b.HasOne("ParliamentApp.Models.Entities.ParliamentPeriod", null)
                        .WithMany("MembersOfParliament")
                        .HasForeignKey("ParliamentPeriodId");
                });

            modelBuilder.Entity("ParliamentApp.Models.MemberVote", b =>
                {
                    b.HasOne("ParliamentApp.Models.MemberOfParliament", "MemberOfParliament")
                        .WithMany()
                        .HasForeignKey("MemberOfParliamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ParliamentApp.Models.Vote", "Vote")
                        .WithMany("MemberVotes")
                        .HasForeignKey("VoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MemberOfParliament");

                    b.Navigation("Vote");
                });

            modelBuilder.Entity("ParliamentApp.Models.Vote", b =>
                {
                    b.HasOne("ParliamentApp.Models.Entities.ParliamentPeriod", "ParliamentPeriod")
                        .WithMany("Votes")
                        .HasForeignKey("ParliamentPeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParliamentPeriod");
                });

            modelBuilder.Entity("ParliamentApp.Models.Entities.ParliamentPeriod", b =>
                {
                    b.Navigation("MembersOfParliament");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("ParliamentApp.Models.Vote", b =>
                {
                    b.Navigation("MemberVotes");
                });
#pragma warning restore 612, 618
        }
    }
}
